---
channels:
  - conda-forge
dependencies:
  # Jupyter
  - jupyterlab=3.1
  - jupyterlab_code_formatter=1.4
  - nodejs=12
  - nbconvert=6
  # RTC
  - jupyterlab-link-share
  # Python Kernel
  - python=3
  - ipykernel=5
  - ipywidgets=7
  - widgetsnbextension=3
  - traittypes=0.2
  - black
  - isort
  - pip
  # Datasets/Graphs
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - pyyaml
  # Ansible
  - ansible
  - pip:
      - git+https://github.com/ansible/ansible-jupyter-kernel.git#egg=ansible-kernel
      - ipynb
